baseURL = 'https://farmfinders.ca/'
languageCode = 'en-us'
title = 'Farm Finders - Canadian Farm Directory'
theme = 'farmfinders'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
