baseURL = "https://farmfinders.ca"
languageCode = "en-ca"
title = "Farms Finder"
theme= "farmfinders"

# Disable unused taxonomies
disableKinds = ["taxonomy", "term", "category"]

[params]
  googleMapsApiKey = "AIzaSyCjA7seTNfSd-MypolPjrg6Q6648TSCvTE"
  googleAnalytics = "G-L59ST3D8JW"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
